theme: minima

title: Origami Folders at UC San Diego
url: origamiucsd.github.io

discord: https://discord.gg/PfdyQ4X5e7
email: origamifoldersucsd@gmail.com
instagram_username: origamifoldersatucsd
youtube_username: origamifoldersucsd5321
