theme: minima

title: Origami Folders at UC San Diego
url: origami.ucsd.edu

discord: https://discord.gg/PfdyQ4X5e7
email: origami@ucsd.edu
instagram_username: origamifoldersucsd
youtube_username: origamifoldersucsd5321
